
#ifndef __HOAGS_CHIMNEY_H__
#define __HOAGS_CHIMNEY_H__

#include "env.h"
#include "hoags_config.h"
#include "packets.h"
#include "htap_config.h"
#include "queue.h"

#define MAX_INTERRUPT_COUNT	50
//
#define MBED_I2C_SLAVE_ADDR0    0x20
//#define MBED_I2C_SLAVE_ADDR1    0x20	//for 16bit address

//#define MBED_I2C_SLAVE_ADDR1	0x21
#define MBED_I2C_BUS_CLK        60000  //hz
//#define I2C_TIMEOUT 500

#define TEMP_SENSOR_I2C_ADDRESS  0x48

enum hoagsIrqDevice
{
	HOAGSIRQ_FAN,
	HOAGSIRQ_AC,
	HOAGSIRQ_COOLER,
	HOAGSIRQ_CHIMNEY
};



//Suvarna: this is mainly for livpure chimney
enum hoagsIrqAction
{
	HOAGSIRQ_CHIMNEY_POWERON,
	HOAGSIRQ_CHIMNEY_POWEROFF,
	HOAGSIRQ_CHIMNEY_POWERON_IR,
	HOAGSIRQ_CHIMNEY_POWEROFF_IR,
	HOAGSIRQ_CHIMNEY_POWERON_LV,
	HOAGSIRQ_CHIMNEY_POWEROFF_LV,
	HOAGSIRQ_CHIMNEY_LIGHTON,
	HOAGSIRQ_CHIMNEY_LIGHTOFF,
	HOAGSIRQ_CHIMNEY_FAN_LOW,
	HOAGSIRQ_CHIMNEY_FAN_MEDIUM,
	HOAGSIRQ_CHIMNEY_FAN_HIGH,
	HOAGSIRQ_CHIMNEY_TIMER_4MINS,
	HOAGSIRQ_CHIMNEY_TIMER_10MINS,
	HOAGSIRQ_CHIMNEY_AUTOCLEAN,
	HOAGSIRQ_CHIMNEY_KEY1_PRESSED,
	HOAGSIRQ_CHIMNEY_KEY2_PRESSED,
	HOAGSIRQ_CHIMNEY_KEY3_PRESSED,
	HOAGSIRQ_CHIMNEY_KEY4_PRESSED,
	HOAGSIRQ_CHIMNEY_KEY5_PRESSED,
	HOAGSIRQ_CHIMNEY_KEY6_PRESSED,
	HOAGSIRQ_CHIMNEY_SMOKE_DETECTED1,
	HOAGSIRQ_CHIMNEY_SMOKE_DETECTED2,
	HOAGSIRQ_CHIMNEY_NO_SMOKE_DETECTED,
	HOAGSIRQ_CHIMNEY_MODE_AUTO,
	HOAGSIRQ_CHIMNEY_MODE_MANNUAL,
	HOAGSIRQ_CHIMNEY_IR_LOCK,


};

struct hoagsIrq
{
	enum hoagsIrqDevice devType;
	enum hoagsIrqAction action;

};

enum CHIMNEY_POWER_CONTROL {
	CHIMNEY_POWER_ON,
	CHIMNEY_POWER_OFF,
};

enum CHIMNEY_FAN_CONTROL {
	CHIMNEY_FAN_LOW,
	CHIMNEY_FAN_MEDIUM, 
	CHIMNEY_FAN_HIGH, 
	CHIMNEY_FAN_TURBO, 
};

enum CHIMNEY_LED_CONTROL {
	CHIMNEY_LED_ON,
	CHIMNEY_LED_OFF,
};

enum CHIMNEY_AUTOCLEAN_CONTROL {
	CHIMNEY_AUTOCLEAN_ON,
	CHIMNEY_AUTOCLEAN_OFF,
};

enum CHIMNEY_MODE {
	CHIMNEY_MODE_AUTO,
	CHIMNEY_MODE_MANNUAL,
};

enum CHIMNEY_SMOKE_HEIGHT_CONTROL {
	CHIMNEY_MIN_HEIGHT,
	CHIMNEY_MEDIUM_HEIGHT,
	CHIMNEY_MAX_HEIGHT,
};

enum CHIMNEY_CMD {
	CHIMNEY_CMD_POWER_CONTROL,
    CHIMNEY_CMD_FANSPEED_CONTROL,
    CHIMNEY_CMD_LED_CONTROL,
	CHIMNEY_CMD_AUTOCLEAN_CONTROL,
	CHIMNEY_CMD_MODE,
	CHIMNEY_SMOKE_HEIGHT_CONTROL,
};



#endif	//__HOAGS_CHIMNEY_H__
