#ifndef __HOAGS_ENV_H__
#define __HOAGS_ENV_H__

#include "basic_types.h"
#include "hoags_config.h"
#include "FreeRTOS.h"
#include "queue.h"
#include "fatfs_flash_api.h"

#define ENVUSER "envusr.bin"

//#include "ameba_ota.h"

#define APPEND    1
#define OVERWRITE 0
#define SUVARNA_LOGS_ENV  0

//Suvarna: To be referred using macro all throughout the codebase, avoid using raw envname directly
#define ENV_SSID                  "ssid"
#define ENV_FWVERSION             "fwversion"
#define ENV_RESERVED_1           "reserved1"
#define ENV_BLEPASSWORD           "blepasskey"
#define ENV_RESERVED_3            "reserved3"
#define ENV_RESERVED_4            "reserved4"
#define ENV_RESERVED_5            "reserved5"
#define ENV_SERIALNO            "serialno"
#define HOT_TEMPERATURE            "hotTempertaure"
#define ENV_USERID                "userid"
#define WARM_TEMPERATURE            "warmTempertaure"
#define CHILDLOCKSTATE            "childlockstate"
#define ENV_FRIENDLYNAME          "friendlyname"
#define ENV_CUSTNAME              "custname"
#define ENV_PRODTYPE              "prodtype"
#define ENV_PRODMODEL             "prodmodel"
#define ENV_USERID                "userid"
#define ENV_RESERVED_11            "reserved11"
#define ENV_RESERVED_12            "reserved12"
#define ENV_RESERVED_13            "reserved13"
#define ENV_RESERVED_14            "reserved14"
#define GLASS_CUST            "glass_cust"
#define BOTTLE_CUST            "bottle_cust"
#define INLET_TDS            "inlet_tds"
#define INLET_TDS_OFFSET            "inlet_tds_offset"
#define OUTLET_TDS            "outlet_tds"
#define ENV_RESERVED_20            "reserved20"
#define ENV_LIFESPAN              "lifespan"
#define ENV_MICMUTE               "micmute"
#define ENV_POWERCONTROL          "pwrctrl"
#define ENV_MODECONTROL           "modectrl"
#define ENV_SPEEDCONTROL          "speedctrl"
#define ENV_TEMPCONTROL           "tempctrl"
#define ENV_MODEVALUE             "modevalue"
#define ENV_SCHEDULER             "scheduler"
#define ENV_LEDCONTROL            "ledctrl"
#define ENV_BUZZER                "buzzerctrl"
#define ENV_REVERSE                "reversectrl"
#define ENV_RESERVED_25            "reserved25"
#define ENV_RESERVED_26            "reserved26"
#define ENV_RESERVED_27            "reserved27"
#define ENV_RESERVED_28            "reserved28"
#define ENV_RESERVED_29            "reserved29"
#define ENV_RESERVED_30            "reserved30"
#define ENV_DEF_MODEL             "defmodel"
#define ENV_UPLOAD_INTERVAL       "uploadinterval"
#define ENV_LAST_TIME             "lasttime"
#define ENV_RESERVED_31            "reserved31"
#define ENV_RESERVED_32            "reserved32"
#define ENV_RESERVED_33            "reserved33"
#define ENV_RESERVED_34            "reserved34"
#define ENV_RESERVED_35            "reserved35"
#define ENV_RESERVED_36            "reserved36"
#define ENV_RESERVED_37            "reserved37"
#define ENV_RESERVED_38            "reserved38"
#define ENV_RESERVED_39            "reserved39"
#define ENV_RESERVED_40            "reserved40"
#define ENV_LOCATION              "location"
#define ENV_WW_GRAMMAR_LENGTH     "wwgmrlen"
#define ENV_WW_NET_LENGTH         "wwnetlen"
#define ENV_CMD_GRAMMAR_LENGTH_1  "cmdgmrlen1"
#define ENV_CMD_NET_LENGTH_1      "cmdnetlen1"
#define ENV_CMD_GRAMMAR_LENGTH_2  "cmdgmrlen2"
#define ENV_CMD_NET_LENGTH_2      "cmdnetlen2"
#define ENV_CMD_GRAMMAR_LENGTH_3  "cmdgmrlen3"
#define ENV_CMD_NET_LENGTH_3      "cmdnetlen3"
#define ENV_CMD_GRAMMAR_LENGTH_4  "cmdgmrlen4"
#define ENV_CMD_NET_LENGTH_4      "cmdnetlen4"
#define ENV_CMD_GRAMMAR_LENGTH_5  "cmdgmrlen5"
#define ENV_CMD_NET_LENGTH_5      "cmdnetlen5"
#define ENV_DEF_WW_GRAMMAR_LENGTH     "defwwgmrlen"
#define ENV_DEF_WW_NET_LENGTH         "defwwnetlen"
#define ENV_DEF_CMD_GRAMMAR_LENGTH_1  "defcmdgmrlen1"
#define ENV_DEF_CMD_NET_LENGTH_1      "defcmdnetlen1"
#define ENV_DEF_CMD_GRAMMAR_LENGTH_2  "defcmdgmrlen2"
#define ENV_DEF_CMD_NET_LENGTH_2      "defcmdnetlen2"
#define ENV_DEF_CMD_GRAMMAR_LENGTH_3  "defcmdgmrlen3"
#define ENV_DEF_CMD_NET_LENGTH_3      "defcmdnetlen3"
#define ENV_DEF_CMD_GRAMMAR_LENGTH_4  "defcmdgmrlen4"
#define ENV_DEF_CMD_NET_LENGTH_4      "defcmdnetlen4"
#define ENV_DEF_CMD_GRAMMAR_LENGTH_5  "defcmdgmrlen5"
#define ENV_DEF_CMD_NET_LENGTH_5      "defcmdnetlen5"
#define ENV_RESERVED_41            "reserved41"
#define ENV_RESERVED_42            "reserved42"
#define ENV_RESERVED_43            "reserved43"
#define ENV_RESERVED_44            "reserved44"
#define ENV_RESERVED_45            "reserved45"
#define ENV_RESERVED_46            "reserved46"
#define ENV_RESERVED_47            "reserved47"
#define ENV_RESERVED_48            "reserved48"
#define ENV_RESERVED_49            "reserved49"
#define ENV_RESERVED_50            "reserved50"
#define ENV_RESERVED_51            "reserved51"
#define ENV_RESERVED_52            "reserved52"
#define ENV_RESERVED_53            "reserved53"
#define ENV_RESERVED_54            "reserved54"
#define ENV_RESERVED_55            "reserved55"
#define ENV_RESERVED_56            "reserved56"
#define ENV_RESERVED_57            "reserved57"
#define ENV_RESERVED_58            "reserved58"
#define ENV_RESERVED_59            "reserved59"
#define ENV_RESERVED_60            "reserved60"
#define ENV_RESERVED_61            "reserved61"
#define ENV_RESERVED_62            "reserved62"
#define ENV_RESERVED_63            "reserved63"
#define ENV_RESERVED_64            "reserved64"
#define ENV_RESERVED_65            "reserved65"
#define ENV_RESERVED_66            "reserved66"

#define ENV_FILE_USER               "envusr.bin"
#define ENV_FILE_FAC                "envfac.bin"
#define ENV_FILE_BK                 "envbk.bin"
#define ENV_FILE_TMP                "envtmp.bin"
#define ENV_FILE_RETAIN             "envretain.bin"
#define ENV_FILE_OTA                "envota.bin"
#define PATH_SEPARATOR              '/'

#define MAX_CALLBACK_COUNT    20
#define ENV_RETAIN_MAX_SIZE     512

struct env
{
  char* key;
  char* value;
};

fatfs_flash_params_t fatfs_flash;

#endif //__HOAGS_ENV_H__
