#ifndef __HOAGS_AIRCOOLER_CONTROLS_H__
#define __HOAGS_AIRCOOLER_CONTROLS_H__

#define AMBER0_START_IDENTIFIER 0x57
#define AMBER1_DATA_ATTR        0X31
#define AMBER2_START_DATA       0x0F

#define AMBER3_POWEROFF         0x30
#define AMBER3_POWERON          0X31

#define AMBER4_FANSPEED_LOW     0x31
#define AMBER4_FANSPEED_MID     0x32
#define AMBER4_FANSPEED_HIGH    0x33

#define AMBER5_SWINGOFF         0x30
#define AMBER5_SWINGON          0x31

#define AMBER6_MOSQUITOOFF      0x30
#define AMBER6_MOSQUITOON       0x31

#define AMBER7_PUMPOFF          0x30
#define AMBER7_PUMPON           0x31

#define AMBER_TBD               0x00

#define AMBER17_END_IDENTIFIER  0x45

enum AIRCOOLER_CMD {
    AIRCOOLER_CMD_POWER_CONTROL,
    AIRCOOLER_CMD_SPEED_CONTROL,
    AIRCOOLER_CMD_MODE_CONTROL,
};

enum AIRCOOLER_CMD_POWER {
    AIRCOOLER_CMD_ON,
    AIRCOOLER_CMD_OFF
};

enum AIRCOOLER_CMD_SPEED {
    AIRCOOLER_CMD_SPEED_LOW,
    AIRCOOLER_CMD_SPEED_MID,
    AIRCOOLER_CMD_SPEED_HIGH,
};

enum AIRCOOLER_CMD_MODE {
    AIRCOOLER_CMD_MODE_MOSQUITO,
    AIRCOOLER_CMD_MODE_SWING,
    AIRCOOLER_CMD_MODE_PUMP,
};

enum AIRCOOLER_CMD_MODE_MOSQUITO {
    AIRCOOLER_CMD_MOSQUITO_ON,
    AIRCOOLER_CMD_MOSQUITO_OFF,
};

enum AIRCOOLER_CMD_MODE_SWING {
    AIRCOOLER_CMD_SWING_ON,
    AIRCOOLER_CMD_SWING_OFF,
};

enum AIRCOOLER_CMD_MODE_PUMP {
    AIRCOOLER_CMD_PUMP_ON,
    AIRCOOLER_CMD_PUMP_OFF,
};


#endif